# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Task Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task Tracker
  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'v10', submodules: true
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'v10', submodules: true
end
